### ISSUE TITLE
Bug in parsing of unordered list?

### ISSUE THREAD

**Issue by JVanDenBergh** [amyjko/peruse#112]
I noticed a parsing error in the chapter [Designing information](https://faculty.washington.edu/ajko/books/foundations-of-information/#/designing) of the book *Foundations of Information*.

Is it possible that there is a typo in the parsing of unnumbered lists?

Shouldn't `/^\*+ /` be `/^\* +/` or `/^\*\s+/`? I.e. the space (or whitespace character) should be present at least once after a single bullet?

This regular expression is used in line 266 and without the `^` on line 328 in [parser.js](https://github.com/amyjko/peruse/blob/master/parser.js).

**Comment by amyjko** [comment]
Thanks for catching! Looks like I forgot the `^` when adding support for nested bullets this morning.
