### ISSUE TITLE
Python output only show last line

### ISSUE THREAD

**Issue by amyjko** [amyjko/peruse#242]
Run this program:

```
ssn = [555, 81, 9297]
if (ssn[0]) >= 545 and ssn[0] <= 573:
    print("Born in California")
```

It only prints 9297.

**Comment by orcmid** [comment]
Mmm, not reproduced this way (v3.9.7
![Python-3 9 7-2021-10-30-1009-AmyBug](https://user-images.githubusercontent.com/3372580/139542506-50a8be82-3873-46a1-89b6-5402f1981ec8.png)
)

**Comment by amyjko** [comment]
To clarify, this is in reference not to a standard Python interpreter, but the Skulpt runtime built for browsers:

http://skulpt.org
